# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ImageFilter/ImageFilter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter || ORIG_REF_NAME==ImageFilter} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_processing_system7_0_0/ImageFilter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_processing_system7_0_0 || ORIG_REF_NAME==ImageFilter_processing_system7_0_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_axi_dma_0_0 || ORIG_REF_NAME==ImageFilter_axi_dma_0_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_axi_timer_0_0/ImageFilter_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_axi_timer_0_0 || ORIG_REF_NAME==ImageFilter_axi_timer_0_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_xlconcat_0_0/ImageFilter_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_xlconcat_0_0 || ORIG_REF_NAME==ImageFilter_xlconcat_0_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_xbar_0/ImageFilter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_xbar_0 || ORIG_REF_NAME==ImageFilter_xbar_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_auto_pc_0/ImageFilter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_auto_pc_0 || ORIG_REF_NAME==ImageFilter_auto_pc_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_ps7_0_axi_periph_0/ImageFilter_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_ps7_0_axi_periph_0 || ORIG_REF_NAME==ImageFilter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_rst_ps7_0_100M_0/ImageFilter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_rst_ps7_0_100M_0 || ORIG_REF_NAME==ImageFilter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_xbar_1/ImageFilter_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_xbar_1 || ORIG_REF_NAME==ImageFilter_xbar_1} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_auto_us_0/ImageFilter_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_auto_us_0 || ORIG_REF_NAME==ImageFilter_auto_us_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_auto_us_1/ImageFilter_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_auto_us_1 || ORIG_REF_NAME==ImageFilter_auto_us_1} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_auto_pc_1/ImageFilter_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_auto_pc_1 || ORIG_REF_NAME==ImageFilter_auto_pc_1} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_axi_mem_intercon_0/ImageFilter_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_axi_mem_intercon_0 || ORIG_REF_NAME==ImageFilter_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ImageFilter/ip/ImageFilter_acc_image_filter_0_0/ImageFilter_acc_image_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ImageFilter_acc_image_filter_0_0 || ORIG_REF_NAME==ImageFilter_acc_image_filter_0_0} -quiet] -quiet

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ImageFilter_ooc.xdc
