# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.srcs/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0.xci
# IP: The module: 'ImageFilter_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.srcs/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0.xci
# IP: The module: 'ImageFilter_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/MIHAJLO/faks/dvs/projekat/FINAL/FINAL.gen/sources_1/bd/ImageFilter/ip/ImageFilter_axi_dma_0_0/ImageFilter_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ImageFilter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
